#!/bin/bash
# Helper script to run tests with dummy credential files for confex
export BINANCE_API_KEY=/tmp/BINANCE_API_KEY
export BINANCE_API_SECRET=/tmp/BINANCE_API_SECRET
export BITMEX_API_KEY=/tmp/BITMEX_API_KEY
export BITMEX_API_SECRET=/tmp/BITMEX_API_SECRET
export OKEX_API_KEY=/tmp/OKEX_API_KEY
export OKEX_API_SECRET=/tmp/OKEX_API_SECRET
export OKEX_API_PASSPHRASE=/tmp/OKEX_API_PASSPHRASE
export DERIBIT_CLIENT_ID=/tmp/DERIBIT_CLIENT_ID
export DERIBIT_CLIENT_SECRET=/tmp/DERIBIT_CLIENT_SECRET
export GDAX_API_KEY=/tmp/GDAX_API_KEY
export GDAX_API_SECRET=/tmp/GDAX_API_SECRET
export GDAX_API_PASSPHRASE=/tmp/GDAX_API_PASSPHRASE
export KRAKEN_API_KEY=/tmp/KRAKEN_API_KEY
export KRAKEN_API_SECRET=/tmp/KRAKEN_API_SECRET
export DELTA_EXCHANGE_API_KEY=/tmp/DELTA_EXCHANGE_API_KEY
export DELTA_EXCHANGE_API_SECRET=/tmp/DELTA_EXCHANGE_API_SECRET

# Create dummy credential files if they don't exist
for var in BINANCE_API_KEY BINANCE_API_SECRET BITMEX_API_KEY BITMEX_API_SECRET \
  OKEX_API_KEY OKEX_API_SECRET OKEX_API_PASSPHRASE DERIBIT_CLIENT_ID \
  DERIBIT_CLIENT_SECRET GDAX_API_KEY GDAX_API_SECRET GDAX_API_PASSPHRASE \
  KRAKEN_API_KEY KRAKEN_API_SECRET DELTA_EXCHANGE_API_KEY DELTA_EXCHANGE_API_SECRET; do
  [ -f "/tmp/$var" ] || echo "dummy" > "/tmp/$var"
done

mix test "$@"
